//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BabySSLYInfoEntities : DbContext
    {
        public BabySSLYInfoEntities()
            : base("name=BabySSLYInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BillGoodsReceiptDtl> BillGoodsReceiptDtl { get; set; }
        public virtual DbSet<BillGoodsReceiptHdr> BillGoodsReceiptHdr { get; set; }
        public virtual DbSet<BillPurchaseDtl> BillPurchaseDtl { get; set; }
        public virtual DbSet<BillPurchaseHdr> BillPurchaseHdr { get; set; }
        public virtual DbSet<BuyersAccount> BuyersAccount { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<HotAttributeSet> HotAttributeSet { get; set; }
        public virtual DbSet<Page_Product> Page_Product { get; set; }
        public virtual DbSet<ProAttribute> ProAttribute { get; set; }
        public virtual DbSet<ProductCategory> ProductCategory { get; set; }
        public virtual DbSet<ProductDtl> ProductDtl { get; set; }
        public virtual DbSet<ProductHdr> ProductHdr { get; set; }
        public virtual DbSet<PurchaseDtl> PurchaseDtl { get; set; }
        public virtual DbSet<PurchaseHdr> PurchaseHdr { get; set; }
        public virtual DbSet<Pvuv> Pvuv { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SejAdvancedSearch> SejAdvancedSearch { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<TbOrderDtl> TbOrderDtl { get; set; }
        public virtual DbSet<TbOrderHdr> TbOrderHdr { get; set; }
        public virtual DbSet<TbStore> TbStore { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<UserManage> UserManage { get; set; }
    
        public virtual ObjectResult<GetSequence_Result> GetSequence(string prefix)
        {
            var prefixParameter = prefix != null ?
                new ObjectParameter("prefix", prefix) :
                new ObjectParameter("prefix", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSequence_Result>("GetSequence", prefixParameter);
        }
    
        public virtual int sp_EditCategoryLoc(string pramTable, string pramCurID, string pramFID, string pramSort)
        {
            var pramTableParameter = pramTable != null ?
                new ObjectParameter("pramTable", pramTable) :
                new ObjectParameter("pramTable", typeof(string));
    
            var pramCurIDParameter = pramCurID != null ?
                new ObjectParameter("pramCurID", pramCurID) :
                new ObjectParameter("pramCurID", typeof(string));
    
            var pramFIDParameter = pramFID != null ?
                new ObjectParameter("pramFID", pramFID) :
                new ObjectParameter("pramFID", typeof(string));
    
            var pramSortParameter = pramSort != null ?
                new ObjectParameter("pramSort", pramSort) :
                new ObjectParameter("pramSort", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EditCategoryLoc", pramTableParameter, pramCurIDParameter, pramFIDParameter, pramSortParameter);
        }
    }
}
