//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillGoodsReceiptHdr
    {
        public string Formno { get; set; }
        public string WHID { get; set; }
        public decimal ID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Checker { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string Description { get; set; }
        public string PFormno { get; set; }
        public Nullable<decimal> State { get; set; }
        public string SupplierID { get; set; }
        public string Department { get; set; }
        public string ProductManager { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public string CheckState { get; set; }
    }
}
