//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPurchaseDtl
    {
        public string Sn { get; set; }
        public string WHID { get; set; }
        public decimal ID { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Uid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Formno { get; set; }
        public string RackNo { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Leave { get; set; }
        public Nullable<decimal> Freeze { get; set; }
        public string ParentSn { get; set; }
        public Nullable<bool> Tag { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
