//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public decimal ID { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Uid { get; set; }
        public Nullable<bool> Delete { get; set; }
        public string Path { get; set; }
        public string SKU { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
