//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotAttributeSet
    {
        public int ID { get; set; }
        public Nullable<int> AKID { get; set; }
        public string AttrName { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string CreateUser { get; set; }
        public System.TimeSpan CreateTime { get; set; }
    }
}
