//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDtl
    {
        public decimal ID { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<decimal> Uid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<decimal> AttributeID { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public string MainImage { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string CodeNum { get; set; }
        public Nullable<decimal> AgeBracket { get; set; }
        public int GxQty { get; set; }
    }
}
