//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHdr
    {
        public int ID { get; set; }
        public string SKU { get; set; }
        public string Title { get; set; }
        public string Describe { get; set; }
        public bool Delete { get; set; }
        public int Uid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public int DocID { get; set; }
        public string ManufacturerCode { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string ZImage { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
    }
}
