//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseHdr
    {
        public PurchaseHdr()
        {
            this.PurchaseDtl = new HashSet<PurchaseDtl>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int Uid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Delete { get; set; }
        public string Remark { get; set; }
        public string SupplierCode { get; set; }
        public decimal Freight { get; set; }
        public System.DateTime UseTime { get; set; }
        public string Formno { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<PurchaseDtl> PurchaseDtl { get; set; }
    }
}
