//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pvuv
    {
        public int ID { get; set; }
        public string SKU { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Uid { get; set; }
        public string KeyWord { get; set; }
        public Nullable<int> Impression { get; set; }
        public Nullable<int> Click { get; set; }
        public Nullable<int> Iuv { get; set; }
        public string Crate { get; set; }
        public Nullable<int> AlipayNum { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<System.DateTime> puTime { get; set; }
        public string Roc { get; set; }
        public string ClientType { get; set; }
        public string Account { get; set; }
    }
}
