//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class SejAdvancedSearch
    {
        public int ID { get; set; }
        public string FName { get; set; }
        public Nullable<int> TradingVolume { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<int> HQBaby { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> FatherID { get; set; }
        public Nullable<System.DateTime> CTime { get; set; }
        public string FValue { get; set; }
    }
}
