//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int ID { get; set; }
        public string SupplierID { get; set; }
        public string Linkman { get; set; }
        public string Url { get; set; }
        public string Phone { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Uid { get; set; }
        public bool Delete { get; set; }
        public string Company { get; set; }
    }
}
