//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbOrderDtl
    {
        public int ID { get; set; }
        public string Formno { get; set; }
        public string SKU { get; set; }
        public int Qty { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public int Uid { get; set; }
        public string Sn { get; set; }
        public bool Delete { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string PicPath { get; set; }
    }
}
