//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TbPrototypeDbEntities1 : DbContext
    {
        public TbPrototypeDbEntities1()
            : base("name=TbPrototypeDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TbProduct> TbProduct { get; set; }
        public DbSet<TbProductExtraInfo> TbProductExtraInfo { get; set; }
        public DbSet<TbProductImg> TbProductImg { get; set; }
        public DbSet<TbProductPropImg> TbProductPropImg { get; set; }
    }
}
