//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbProductImg
    {
        public Nullable<int> pid { get; set; }
        public Nullable<int> product_id { get; set; }
        public string url { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> UID { get; set; }
    }
}
