//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbProduct
    {
        public string name { get; set; }
        public string binds { get; set; }
        public string sale_props { get; set; }
        public Nullable<decimal> price { get; set; }
        public string desc { get; set; }
        public string pic_url { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string product_prop_imgs { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> level { get; set; }
        public string pic_path { get; set; }
        public Nullable<int> rate_num { get; set; }
        public Nullable<int> sale_num { get; set; }
        public string shop_price { get; set; }
        public string standard_price { get; set; }
        public Nullable<int> vertical_market { get; set; }
        public string customer_props { get; set; }
        public string property_alias { get; set; }
        public Nullable<int> product_id { get; set; }
        public string outer_id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string tsc { get; set; }
        public Nullable<int> cid { get; set; }
        public string cat_name { get; set; }
        public string props { get; set; }
        public string props_str { get; set; }
        public string binds_str { get; set; }
        public string sale_props_str { get; set; }
        public Nullable<int> collect_num { get; set; }
        public string product_imgs { get; set; }
        public string product_extra_infos { get; set; }
        public string sell_pt { get; set; }
        public string cspu_feature { get; set; }
        public Nullable<int> template_id { get; set; }
        public Nullable<int> commodity_id { get; set; }
        public Nullable<bool> is_suite_effective { get; set; }
        public string suite_items_str { get; set; }
        public string barcode_str { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> UID { get; set; }
    }
}
