//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace zjh.SSLY.Model.Info
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string UName { get; set; }
        public short DelFlag { get; set; }
        public string UserPwd { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime LastModfiedDate { get; set; }
        public System.DateTime LastLoginTime { get; set; }
        public int ErrorCount { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Remark { get; set; }
        public int Role { get; set; }
    }
}
